server:
  port: 8080
  
spring:  application:    name: gate-way  cloud:    gateway:      discovery:        locator:          enabled: true          lower-case-service-id: true
    

management:  endpoints:    web:      exposure:        include:        - "*"      

eureka:  client:    service-url:      defaultZone: htttp://localhost:8761/eureka    
        